### PR TITLE
Fixed kebab casing of previous `appwindow.slint`.

### PR DESCRIPTION
**Pull request by Enyium**

### CODE REVIEW

**Review by tronical — COMMENTED** [review]
I'd prefer to stick with `appwindow.slint` as we use that file name also in the quick start guide and in the other templates that would need to be changed. How strongly do you feel about this change?

**Comment by Enyium** [comment]
For me, it's clear that it must be `app-window.slint` for logical consistency. I use this naming in my productive project. Why condition users to bad habits? `std-widgets.slint` sets the precedent for kebab case, not compact case.

**Comment by tronical** [comment]
In that case, I suggest that we if we go this route (and I'm not objecting), the this needs to be changed in all template repositories as well as the Quick Start Guide. The latter can be done now, but the PRs for the templates would be merged on the day of the release, to avoid that the Quick Start Guide is out of sync with the templates. What you think?

**Comment by Enyium** [comment]
@tronical: Quick answer would be appreciated:

Does `#include "appwindow.h"` in C++ projects become `#include "app_window.h"` or `#include "app-window.h"`?

**Comment by tronical** [comment]
I believe `app-window.slint` will map to `app-window.h` in C++.

**Comment by Enyium** [comment]
@tronical: Thanks. And `appwindow` in this Python-related code? Will it become `app_window`?

```py
# slint.loader will look in `sys.path` for `app-window.slint`.
class App(slint.loader.appwindow.AppWindow):
```

**Comment by tronical** [comment]
Since dashes are not supported in identifiers, the loader API doesn't work anymore. One would have to write something like this:

Old:

```python
class App(slint.loader.appwindow.AppWindow):
```

New:

```python
appwindow_module = getattr(slint.loader, "app-window")
class App(appwindow_module.AppWindow)
```

This is a good argument against using a dash in the file name of `.slint` files in our template (including future Python template). 

Although yes, the Python loader could do a mapping, so `loader.app_window` looks also for `app-window.slint`.

**Comment by Enyium** [comment]
- Does this now mean this change can't land in Slint v1.8 anymore? It would be annoying if this issue would continue to linger with these many repos, instead of solving it now, just because of this Python issue.
- Or may I, for now, use the two lines you wrote under "New"? EDIT: Or, rather:
    ```python
    # class App(slint.loader.app_window.AppWindow): # Supported soon.
    class App(getattr(slint.loader, "app-window").AppWindow):
    ```

> This is a good argument against using a dash in the file name of `.slint` files in our template (including future Python template).

I can't understand that. It's a good argument for the Python loader to do a mapping, IMO. There's a parallel to this kind of mapping in the Cargo context.

**Comment by tronical** [comment]
Yes, I'm not opposed to having such a mapping in the Python loader anyway.

**Comment by tronical** [comment]
Thanks for the changes @Enyium  (also in the other repos). We're a little close to the next release in the next few days, my preference would be to do this after the 1.8 release. I can help then with testing and maybe doing the Quickstart changes. Would that be okay with you?

@ogoffart you ok with this, too?

**Comment by Enyium** [comment]
> I can help then with testing and maybe doing the Quickstart changes.

The quick start changes should be included in this PR: <https://github.com/slint-ui/slint/pull/6213>. Or did you have more in mind?

> Would that be okay with you?

If it were up to me, I would want to be done with it now. But I don't have the decisive power and don't know what problems you may see with this.

**Comment by ogoffart** [comment]
I don't have strong opinions about this. So no objections from me.

**Review by tronical — APPROVED** [review]

**Pull request merged**
